language: python
python:
  - 2.7
  - 3.7

sudo: required
dist: xenial

notifications:
  slack: silab-bonn:nU3pnaHN3RJ6WRFrfjec9vPM
  email:
    - hemperek@uni-bonn.de
    - janssen@physik.uni-bonn.de
    - pohl@physik.uni-bonn.de

before_install:
  # Install cocotb and iverilog for interface test
#  - git clone https://github.com/potentialventures/cocotb
#  - export COCOTB=$(pwd)/cocotb
  # Build iverilog from source
  - sudo apt-get install gperf
  - git clone https://github.com/steveicarus/iverilog.git
  - cd iverilog && autoconf && ./configure && make && sudo make install && cd ..
  # Download iverilog from PPA
#  - sudo add-apt-repository -y ppa:team-electronics/ppa
#  - sudo apt-get -q update
#  - sudo apt-get -q install iverilog-daily
  # Download iverilog from conda-forge
#  - conda config --add channels conda-forge
#  - conda install iverilog

install:
  # conda
  - wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda update --yes --all
  - conda info -a
  - conda create --yes -n test-environment python=$TRAVIS_PYTHON_VERSION numpy bitarray nose pyyaml coverage six flake8
  - source activate test-environment
  - pip install pyvisa pyvisa-sim=0.4 coveralls cocotb==1.2.0 flake8-diff
  # install basil
  - python setup.py develop

script:
  - nosetests --with-coverage --cover-package=basil  tests/test_*.py examples/*/*/test_*.py
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  # Check code style flaws of changed lines
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch
  - if [ "$BRANCH" == "development" ]; then flake8-diff origin/master; else flake8-diff origin/development; fi

after_success:
  - coveralls

deploy:
  provider: pypi
  user: davidlp
  password:
    secure: EWWzZuUU5hJAd9iVPr4kPYbs1wbm7D8eVU596GUH8ZI/Q4seXsYeL+Pi++FI6M268qNUGJuVsvWbU5S+/E74VmIeU3b0n6BNSfUas0tSqMmazN/Sj0iMtGJ3Tll5Z7JfPK2RbZfBvSHN5T9W5RXz7M2US0x88ATrNVt3iuRNqWQ=
  on:
    tags: true
    repo: SiLab-Bonn/basil
  skip_existing: true
  distributions: sdist bdist_wheel
